[colors.primary]
background = '#121212'
foreground = '#d4be98'

[colors.normal]
black = '#32302f'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#d4be98'

[colors.bright]
black = '#32302f'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#d4be98'

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window.padding]
x = 16
y = 8
